[package]
name = "dimina-wxml-parser"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
swc_common = "23.0.0"
swc_ecma_ast = "25.0.0"
swc_ecma_parser = { version = "41.0.0", default-features = false, features = ["typescript"] }
swc_atoms = "9.0"

[dev-dependencies]
