[package]
name = "dimina-wxml-parser-napi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.16", default-features = false, features = ["napi8"] }
napi-derive = "2.16"
serde_json = "1"
swc_common = "23.0.0"
swc_atoms = "9.0"
dimina-wxml-parser = { path = "../dimina-wxml-parser" }

[build-dependencies]
napi-build = "2"
